image: nixos/nix

docs:test:
  stage: test
  script:
    - "nix --experimental-features 'nix-command flakes' develop .#docs -c mkdocs build --strict --verbose --site-dir test"
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

docs:pages:
  stage: deploy
  script:
    - "nix --experimental-features 'nix-command flakes' develop .#docs -c mkdocs build --strict --verbose"
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

test:cargo:
  script:
    - "nix --experimental-features 'nix-command flakes' develop -c mold -run cargo t"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
