image: nixos/nix

docs:test:
  stage: test
  script:
    - nix develop .#docs -c mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

docs:pages:
  stage: deploy
  script:
    - nix develop .#docs -c mkdocs build --strict --verbose
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

test:cargo:
  script:
    - nix develop -c mold -run cargo t
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
